default_config = {
    "cartpole": {
        "env": "CartPole-v0",
        "save_max_eps": False,
        "vf_layers": [
            ("linear", 16, "relu"),
            ("linear", 16, "relu"),
            ("linear", 16, "relu"),
            ("linear", 16, "relu"),
        ],
        "pi_layers": [
            ("linear", 128, "relu"),
            ("linear", 128, "relu"),
            ("linear", 128, "relu"),
        ],
        "pi_lr": 0.003,
        "vf_lr": 0.0015,
        "vf_train_iters": 80,
        "gamma": 0.995,
        "lambda": 0.95,
        "batch_size": 1024,
        "steps": 163840,
        "log_step": 8192,
        "seed": 42,
    },
    "invertedpendulum": {
        "env": "InvertedPendulum-v2",
        "save_max_eps": False,
        "vf_layers": [
            ("linear", 128, "relu"),
            ("linear", 128, "relu"),
        ],
        "pi_layers": [
            ("linear", 64, "relu"),
            ("linear", 64, "relu"),
            ("linear", 64, "relu"),
        ],
        "pi_lr": 0.004,
        "vf_lr": 0.1,
        "vf_train_iters": 320,
        "std_logits": -0.5,
        "gamma": 0.995,
        "lambda": 0.99,
        "batch_size": 1024,
        "steps": 163840,
        "log_step": 8192,
        "seed": 42,
    },
    "frozenlake": {
        "env": "FrozenLake-v1",
        "env_args": {
            "is_slippery": False,
        },
        "save_max_eps": False,
        "vf_layers": [
            ("embed", 16, 8),
            ("linear", 128, "relu"),
            ("linear", 128, "relu"),
            ("linear", 128, "relu"),
            ("linear", 128, "relu"),
        ],
        "pi_layers": [
            ("embed", 16, 8),
            ("linear", 256, "relu"),
            ("linear", 256, "relu"),
            ("linear", 256, "relu"),
        ],
        "pi_lr": 0.0022,
        "vf_lr": 0.004,
        "vf_train_iters": 80,
        "gamma": 0.99,
        "lambda": 0.97,
        "batch_size": 2048,
        "steps": 491520,
        "log_step": 8192,
        "seed": 42,
    },
    "halfcheetah": {
        "env": "HalfCheetah-v2",
        "save_max_eps": False,
        "vf_layers": [
            ("linear", 128, "relu"),
            ("linear", 128, "relu"),
        ],
        "pi_layers": [
            ("linear", 64, "relu"),
            ("linear", 64, "relu"),
            ("linear", 64, "relu"),
        ],
        "pi_lr": 0.004,
        "vf_lr": 0.1,
        "vf_train_iters": 320,
        "std_logits": -0.5,
        "gamma": 0.995,
        "lambda": 0.99,
        "batch_size": 1024,
        "steps": 163840,
        "log_step": 8192,
        "seed": 42,
    },
}
